Resources:
  MiInstancia:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0abcdef1234567890
      IamInstanceProfile: LabInstanceProfile
  MiBucket:
    Type: AWS::S3::Bucket
Outputs:
  BucketName:
    Value: !Ref MiBucket
